services:
  explorer-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "example_dev"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres:
    driver: local