defmodule Example.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:components, primary_key: false) do
      add :code, :text, null: false, primary_key: true
      add :target_version, :text, null: false
    end
  end

  def down do
    drop table(:components)
  end
end